version: '3.8'

services:
 db:
   image: mysql
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: test
   ports:
     - "3307:3306"
   networks:
     - mynetwork

 myapp:
   image: myapp
   ports:
     - "8083:8080"
   environment:
     - MYSQL_HOST=db
     - MYSQL_PORT=3306
     - MYSQL_USER=root
     - MYSQL_PASSWORD=root
   depends_on:
     - db
   networks:
     - mynetwork

networks:
 mynetwork:
# version: '3.7'

# services:

#   app:
#     image: myapp
#     ports:
#       - "8083:8080"
#     depends_on:
#       - db
#     environment:
#       - MYSQL_HOST=db
#       - MYSQL_PORT=3306
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=root
#     networks:
#       - mynetwork


#   db:
#     image: mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: test
#     ports:
#       - "3307:3306"
#     volumes:
#       - ./mysql:/var/lib/mysql
#     networks:
#       - mynetwork

# networks:
#   mynetwork:
#     name: mynetworkapp
